//subsequence of a string : generated by deleting zero or more 
//letters from the string and keeping the rest of letters in same order

#include<iostream>
#include<bits/stdc++.h>

using namespace std;

void solve(string str,vector<string> &ans,int index,string output){
    //base case
    if(index >= str.length()){
        if(output.length() > 0){ //here empty set won't be considered
            ans.push_back(output);
        }
        return;
    }
    //exclude
    solve(str,ans,index+1,output);

    //include
    char element = str[index];
    output.push_back(element);
    solve(str,ans,index+1,output);
}

int main(){
    string str = "abc";
    vector<string> ans;
    string output;
    int index = 0;

    solve(str,ans,index,output);

    for(const auto& subsequence : ans){
        for(const auto& val : subsequence){
            cout<<val<<" ";
        }
        cout<<endl;
    }
    return 0;
}